In [1]:
import pandas as pd
import numpy as np

In [2]:
data = "Academic Performance.csv"
df = pd.read_csv(data)

In [3]:
df

,Math Score,Reading Score,Writing Score,Placement Score,Club Join Year,Placement,Offer Count
0,95,81,93,85,96,98,99
1,83,79,64,97,79,66,97
2,100,96,70,86,99,84,69
3,88,83,100,81,62,79,79
4,73,72,96,62,85,64,64
5,63,76,84,100,92,83,74
6,72,87,99,94,99,72,68
7,90,75,91,66,67,88,86
8,97,79,74,77,84,90,91
9,74,60,77,70,77,81,69
10,77,65,61,90,61,60,67
11,75,94,88,91,63,90,71
12,85,79,63,93,61,99,80
13,80,79,100,71,75,76,95
14,81,81,88,61,90,91,84
15,80,64,98,100,90,69,96
16,66,85,94,84,83,60,62
17,99,80,75,93,67,72,76
18,85,87,81,99,96,63,73
19,76,99,89,84,66,97,87

In [4]:
df.isnull()

,Math Score,Reading Score,Writing Score,Placement Score,Club Join Year,Placement,Offer Count
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False

In [5]:
series = pd.isnull(df["Math Score"])
df[series]

Empty DataFrame
Columns: [Math Score, Reading Score, Writing Score, Placement Score, Club Join Year, Placement, Offer Count]
Index: []

In [6]:
df.notnull()

,Math Score,Reading Score,Writing Score,Placement Score,Club Join Year,Placement,Offer Count
0,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True

In [7]:
series1 = pd.notnull(df["Math Score"])
df[series1]

,Math Score,Reading Score,Writing Score,Placement Score,Club Join Year,Placement,Offer Count
0,95,81,93,85,96,98,99
1,83,79,64,97,79,66,97
2,100,96,70,86,99,84,69
3,88,83,100,81,62,79,79
4,73,72,96,62,85,64,64
5,63,76,84,100,92,83,74
6,72,87,99,94,99,72,68
7,90,75,91,66,67,88,86
8,97,79,74,77,84,90,91
9,74,60,77,70,77,81,69
10,77,65,61,90,61,60,67
11,75,94,88,91,63,90,71
12,85,79,63,93,61,99,80
13,80,79,100,71,75,76,95
14,81,81,88,61,90,91,84
15,80,64,98,100,90,69,96
16,66,85,94,84,83,60,62
17,99,80,75,93,67,72,76
18,85,87,81,99,96,63,73
19,76,99,89,84,66,97,87

In [12]:
!pip install scikit-learn

Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/f6/28/b569523552a11b49dc4d33952f43dedb23792fe8ce2f2151d070d615861a/scikit_learn-1.4.0-1-cp312-cp312-win_amd64.whl.metadata
  Downloading scikit_learn-1.4.0-1-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.0,>=1.19.5 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.26.3)
Collecting scipy>=1.6.0 (from scikit-learn)
  Obtaining dependency information for scipy>=1.6.0 from https://files.pythonhosted.org/packages/f3/31/91a2a3c5eb85d2bfa86d7c98f2df5d77dcdefb3d80ca9f9037ad04393acf/scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata
  Downloading scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.4 kB ? eta -:--:--
     -------------------------------- ----- 51.2/60.4 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 60.4/60.4 kB 643.6 kB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn)
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
Downloading scikit_learn-1.4.0-1-cp312-cp312-win_amd64.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.6 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.4/10.6 MB 4.9 MB/s eta 0:00:03
   -- ------------------------------------- 0.7/10.6 MB 4.9 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/10.6 MB 4.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.2/10.6 MB 5.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/10.6 MB 5.8 MB/s eta 0:00:02
   ------ --------------------------------- 1.8/10.6 MB 5.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/10.6 MB 5.8 MB/s eta 0:00:02
   --------- ------------------------------ 2.5/10.6 MB 6.1 MB/s eta 0:00:02
   ---------- ----------------------------- 2.8/10.6 MB 6.1 MB/s eta 0:00:02
   ----------- ---------------------------- 3.0/10.6 MB 6.3 MB/s eta 0:00:02
   ------------ --------------------------- 3.3/10.6 MB 6.1 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/10.6 MB 6.2 MB/s eta 0:00:02
   --------------- ------------------------ 4.0/10.6 MB 6.3 MB/s eta 0:00:02
   ---------------- ----------------------- 4.4/10.6 MB 6.2 MB/s eta 0:00:02
   ----------------- ---------------------- 4.6/10.6 MB 6.3 MB/s eta 0:00:01
   ------------------ --------------------- 4.9/10.6 MB 6.2 MB/s eta 0:00:01
   ------------------- -------------------- 5.3/10.6 MB 6.3 MB/s eta 0:00:01
   --------------------- ------------------ 5.6/10.6 MB 6.3 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.3 MB/s eta 0:00:01
   ----------------------- ---------------- 6.2/10.6 MB 6.3 MB/s eta 0:00:01
   ------------------------ --------------- 6.5/10.6 MB 6.3 MB/s eta 0:00:01
   ------------------------- -------------- 6.8/10.6 MB 6.3 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 6.3 MB/s eta 0:00:01
   ---------------------------- ----------- 7.4/10.6 MB 6.3 MB/s eta 0:00:01
   ----------------------------- ---------- 7.7/10.6 MB 6.4 MB/s eta 0:00:01
   ------------------------------ --------- 8.0/10.6 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 8.3/10.6 MB 6.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.6 MB 6.4 MB/s eta 0:00:01
   --------------------------------- ------ 9.0/10.6 MB 6.4 MB/s eta 0:00:01
   ----------------------------------- ---- 9.3/10.6 MB 6.4 MB/s eta 0:00:01
   ------------------------------------ --- 9.6/10.6 MB 6.4 MB/s eta 0:00:01
   ------------------------------------- -- 9.9/10.6 MB 6.3 MB/s eta 0:00:01
   -------------------------------------- - 10.2/10.6 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------  10.5/10.6 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 6.4 MB/s eta 0:00:00
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   ---------------------------------------- 0.0/302.2 kB ? eta -:--:--
   ---------------------------------------  297.0/302.2 kB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 302.2/302.2 kB 6.2 MB/s eta 0:00:00
Downloading scipy-1.12.0-cp312-cp312-win_amd64.whl (45.8 MB)
   ---------------------------------------- 0.0/45.8 MB ? eta -:--:--
   ---------------------------------------- 0.5/45.8 MB 9.4 MB/s eta 0:00:05
    --------------------------------------- 0.8/45.8 MB 9.8 MB/s eta 0:00:05
    --------------------------------------- 1.0/45.8 MB 8.2 MB/s eta 0:00:06
   - -------------------------------------- 1.3/45.8 MB 8.2 MB/s eta 0:00:06
   - -------------------------------------- 1.6/45.8 MB 7.0 MB/s eta 0:00:07
   - -------------------------------------- 2.1/45.8 MB 7.4 MB/s eta 0:00:06
   -- ------------------------------------- 2.3/45.8 MB 7.1 MB/s eta 0:00:07
   -- ------------------------------------- 2.6/45.8 MB 7.2 MB/s eta 0:00:06
   -- ------------------------------------- 2.9/45.8 MB 7.0 MB/s eta 0:00:07
   -- ------------------------------------- 3.1/45.8 MB 7.1 MB/s eta 0:00:06
   -- ------------------------------------- 3.4/45.8 MB 7.0 MB/s eta 0:00:07
   --- ------------------------------------ 3.7/45.8 MB 7.1 MB/s eta 0:00:06
   --- ------------------------------------ 3.9/45.8 MB 6.9 MB/s eta 0:00:07
   --- ------------------------------------ 4.2/45.8 MB 6.7 MB/s eta 0:00:07
   --- ------------------------------------ 4.5/45.8 MB 6.7 MB/s eta 0:00:07
   ---- ----------------------------------- 5.0/45.8 MB 6.9 MB/s eta 0:00:06
   ---- ----------------------------------- 5.2/45.8 MB 6.8 MB/s eta 0:00:06
   ---- ----------------------------------- 5.5/45.8 MB 6.7 MB/s eta 0:00:06
   ----- ---------------------------------- 5.8/45.8 MB 6.6 MB/s eta 0:00:07
   ----- ---------------------------------- 6.2/45.8 MB 6.8 MB/s eta 0:00:06
   ----- ---------------------------------- 6.5/45.8 MB 6.8 MB/s eta 0:00:06
   ----- ---------------------------------- 6.8/45.8 MB 6.8 MB/s eta 0:00:06
   ------ --------------------------------- 7.0/45.8 MB 6.7 MB/s eta 0:00:06
   ------ --------------------------------- 7.4/45.8 MB 6.6 MB/s eta 0:00:06
   ------ --------------------------------- 7.8/45.8 MB 6.7 MB/s eta 0:00:06
   ------- -------------------------------- 8.1/45.8 MB 6.7 MB/s eta 0:00:06
   ------- -------------------------------- 8.4/45.8 MB 6.8 MB/s eta 0:00:06
   ------- -------------------------------- 8.6/45.8 MB 6.6 MB/s eta 0:00:06
   ------- -------------------------------- 9.0/45.8 MB 6.7 MB/s eta 0:00:06
   -------- ------------------------------- 9.4/45.8 MB 6.7 MB/s eta 0:00:06
   -------- ------------------------------- 9.7/45.8 MB 6.7 MB/s eta 0:00:06
   -------- ------------------------------- 9.9/45.8 MB 6.8 MB/s eta 0:00:06
   -------- ------------------------------- 10.2/45.8 MB 6.7 MB/s eta 0:00:06
   --------- ------------------------------ 10.5/45.8 MB 6.6 MB/s eta 0:00:06
   --------- ------------------------------ 10.9/45.8 MB 6.5 MB/s eta 0:00:06
   --------- ------------------------------ 11.2/45.8 MB 6.6 MB/s eta 0:00:06
   ---------- ----------------------------- 11.5/45.8 MB 6.5 MB/s eta 0:00:06
   ---------- ----------------------------- 11.8/45.8 MB 6.5 MB/s eta 0:00:06
   ---------- ----------------------------- 12.1/45.8 MB 6.6 MB/s eta 0:00:06
   ---------- ----------------------------- 12.4/45.8 MB 6.5 MB/s eta 0:00:06
   ----------- ---------------------------- 12.6/45.8 MB 6.6 MB/s eta 0:00:06
   ----------- ---------------------------- 12.9/45.8 MB 6.5 MB/s eta 0:00:06
   ----------- ---------------------------- 13.2/45.8 MB 6.6 MB/s eta 0:00:05
   ----------- ---------------------------- 13.5/45.8 MB 6.5 MB/s eta 0:00:05
   ------------ --------------------------- 13.8/45.8 MB 6.5 MB/s eta 0:00:05
   ------------ --------------------------- 14.1/45.8 MB 6.5 MB/s eta 0:00:05
   ------------ --------------------------- 14.4/45.8 MB 6.6 MB/s eta 0:00:05
   ------------ --------------------------- 14.8/45.8 MB 6.6 MB/s eta 0:00:05
   ------------- -------------------------- 15.1/45.8 MB 6.5 MB/s eta 0:00:05
   ------------- -------------------------- 15.4/45.8 MB 6.5 MB/s eta 0:00:05
   ------------- -------------------------- 15.6/45.8 MB 6.5 MB/s eta 0:00:05
   ------------- -------------------------- 15.9/45.8 MB 6.5 MB/s eta 0:00:05
   -------------- ------------------------- 16.2/45.8 MB 6.5 MB/s eta 0:00:05
   -------------- ------------------------- 16.5/45.8 MB 6.5 MB/s eta 0:00:05
   -------------- ------------------------- 16.8/45.8 MB 6.5 MB/s eta 0:00:05
   --------------- ------------------------ 17.2/45.8 MB 6.6 MB/s eta 0:00:05
   --------------- ------------------------ 17.5/45.8 MB 6.5 MB/s eta 0:00:05
   --------------- ------------------------ 17.8/45.8 MB 6.5 MB/s eta 0:00:05
   --------------- ------------------------ 18.1/45.8 MB 6.6 MB/s eta 0:00:05
   ---------------- ----------------------- 18.4/45.8 MB 6.6 MB/s eta 0:00:05
   ---------------- ----------------------- 18.8/45.8 MB 6.5 MB/s eta 0:00:05
   ---------------- ----------------------- 19.0/45.8 MB 6.5 MB/s eta 0:00:05
   ---------------- ----------------------- 19.4/45.8 MB 6.5 MB/s eta 0:00:05
   ----------------- ---------------------- 19.7/45.8 MB 6.5 MB/s eta 0:00:04
   ----------------- ---------------------- 19.9/45.8 MB 6.6 MB/s eta 0:00:04
   ----------------- ---------------------- 20.3/45.8 MB 6.5 MB/s eta 0:00:04
   ----------------- ---------------------- 20.6/45.8 MB 6.5 MB/s eta 0:00:04
   ------------------ --------------------- 20.9/45.8 MB 6.5 MB/s eta 0:00:04
   ------------------ --------------------- 21.2/45.8 MB 6.5 MB/s eta 0:00:04
   ------------------ --------------------- 21.5/45.8 MB 6.6 MB/s eta 0:00:04
   ------------------- -------------------- 21.9/45.8 MB 6.5 MB/s eta 0:00:04
   ------------------- -------------------- 22.2/45.8 MB 6.5 MB/s eta 0:00:04
   ------------------- -------------------- 22.5/45.8 MB 6.7 MB/s eta 0:00:04
   ------------------- -------------------- 22.8/45.8 MB 6.6 MB/s eta 0:00:04
   -------------------- ------------------- 23.1/45.8 MB 6.5 MB/s eta 0:00:04
   -------------------- ------------------- 23.4/45.8 MB 6.6 MB/s eta 0:00:04
   -------------------- ------------------- 23.8/45.8 MB 6.5 MB/s eta 0:00:04
   -------------------- ------------------- 24.0/45.8 MB 6.5 MB/s eta 0:00:04
   --------------------- ------------------ 24.4/45.8 MB 6.6 MB/s eta 0:00:04
   --------------------- ------------------ 24.6/45.8 MB 6.6 MB/s eta 0:00:04
   --------------------- ------------------ 25.0/45.8 MB 6.5 MB/s eta 0:00:04
   ---------------------- ----------------- 25.3/45.8 MB 6.6 MB/s eta 0:00:04
   ---------------------- ----------------- 25.6/45.8 MB 6.5 MB/s eta 0:00:04
   ---------------------- ----------------- 25.9/45.8 MB 6.5 MB/s eta 0:00:04
   ---------------------- ----------------- 26.2/45.8 MB 6.5 MB/s eta 0:00:03
   ----------------------- ---------------- 26.5/45.8 MB 6.5 MB/s eta 0:00:03
   ----------------------- ---------------- 26.8/45.8 MB 6.5 MB/s eta 0:00:03
   ----------------------- ---------------- 27.2/45.8 MB 6.5 MB/s eta 0:00:03
   ------------------------ --------------- 27.5/45.8 MB 6.5 MB/s eta 0:00:03
   ------------------------ --------------- 27.8/45.8 MB 6.5 MB/s eta 0:00:03
   ------------------------ --------------- 28.2/45.8 MB 6.5 MB/s eta 0:00:03
   ------------------------ --------------- 28.5/45.8 MB 6.6 MB/s eta 0:00:03
   ------------------------- -------------- 28.8/45.8 MB 6.5 MB/s eta 0:00:03
   ------------------------- -------------- 29.2/45.8 MB 6.6 MB/s eta 0:00:03
   ------------------------- -------------- 29.5/45.8 MB 6.5 MB/s eta 0:00:03
   -------------------------- ------------- 29.8/45.8 MB 6.6 MB/s eta 0:00:03
   -------------------------- ------------- 30.1/45.8 MB 6.5 MB/s eta 0:00:03
   -------------------------- ------------- 30.4/45.8 MB 6.5 MB/s eta 0:00:03
   -------------------------- ------------- 30.7/45.8 MB 6.5 MB/s eta 0:00:03
   --------------------------- ------------ 30.9/45.8 MB 6.6 MB/s eta 0:00:03
   --------------------------- ------------ 31.2/45.8 MB 6.5 MB/s eta 0:00:03
   --------------------------- ------------ 31.5/45.8 MB 6.6 MB/s eta 0:00:03
   --------------------------- ------------ 31.8/45.8 MB 6.6 MB/s eta 0:00:03
   ---------------------------- ----------- 32.1/45.8 MB 6.6 MB/s eta 0:00:03
   ---------------------------- ----------- 32.4/45.8 MB 6.6 MB/s eta 0:00:03
   ---------------------------- ----------- 32.7/45.8 MB 6.5 MB/s eta 0:00:03
   ---------------------------- ----------- 32.9/45.8 MB 6.6 MB/s eta 0:00:02
   ----------------------------- ---------- 33.2/45.8 MB 6.6 MB/s eta 0:00:02
   ----------------------------- ---------- 33.5/45.8 MB 6.6 MB/s eta 0:00:02
   ----------------------------- ---------- 33.8/45.8 MB 6.5 MB/s eta 0:00:02
   ----------------------------- ---------- 34.1/45.8 MB 6.5 MB/s eta 0:00:02
   ----------------------------- ---------- 34.3/45.8 MB 6.5 MB/s eta 0:00:02
   ------------------------------ --------- 34.6/45.8 MB 6.6 MB/s eta 0:00:02
   ------------------------------ --------- 34.9/45.8 MB 6.6 MB/s eta 0:00:02
   ------------------------------ --------- 35.2/45.8 MB 6.5 MB/s eta 0:00:02
   ------------------------------- -------- 35.6/45.8 MB 6.5 MB/s eta 0:00:02
   ------------------------------- -------- 35.8/45.8 MB 6.6 MB/s eta 0:00:02
   ------------------------------- -------- 36.1/45.8 MB 6.6 MB/s eta 0:00:02
   ------------------------------- -------- 36.4/45.8 MB 6.6 MB/s eta 0:00:02
   -------------------------------- ------- 36.7/45.8 MB 6.6 MB/s eta 0:00:02
   -------------------------------- ------- 37.0/45.8 MB 6.6 MB/s eta 0:00:02
   -------------------------------- ------- 37.4/45.8 MB 6.6 MB/s eta 0:00:02
   -------------------------------- ------- 37.6/45.8 MB 6.6 MB/s eta 0:00:02
   --------------------------------- ------ 38.0/45.8 MB 6.5 MB/s eta 0:00:02
   --------------------------------- ------ 38.3/45.8 MB 6.5 MB/s eta 0:00:02
   --------------------------------- ------ 38.7/45.8 MB 6.7 MB/s eta 0:00:02
   --------------------------------- ------ 38.9/45.8 MB 6.6 MB/s eta 0:00:02
   ---------------------------------- ----- 39.2/45.8 MB 6.6 MB/s eta 0:00:02
   ---------------------------------- ----- 39.5/45.8 MB 6.6 MB/s eta 0:00:01
   ---------------------------------- ----- 39.7/45.8 MB 6.5 MB/s eta 0:00:01
   ---------------------------------- ----- 40.1/45.8 MB 6.6 MB/s eta 0:00:01
   ----------------------------------- ---- 40.3/45.8 MB 6.5 MB/s eta 0:00:01
   ----------------------------------- ---- 40.6/45.8 MB 6.6 MB/s eta 0:00:01
   ----------------------------------- ---- 40.9/45.8 MB 6.6 MB/s eta 0:00:01
   ----------------------------------- ---- 41.2/45.8 MB 6.6 MB/s eta 0:00:01
   ------------------------------------ --- 41.4/45.8 MB 6.6 MB/s eta 0:00:01
   ------------------------------------ --- 41.7/45.8 MB 6.6 MB/s eta 0:00:01
   ------------------------------------ --- 41.9/45.8 MB 6.6 MB/s eta 0:00:01
   ------------------------------------ --- 42.2/45.8 MB 6.6 MB/s eta 0:00:01
   ------------------------------------- -- 42.5/45.8 MB 6.6 MB/s eta 0:00:01
   ------------------------------------- -- 42.8/45.8 MB 6.6 MB/s eta 0:00:01
   ------------------------------------- -- 43.0/45.8 MB 6.5 MB/s eta 0:00:01
   ------------------------------------- -- 43.4/45.8 MB 6.5 MB/s eta 0:00:01
   -------------------------------------- - 43.7/45.8 MB 6.6 MB/s eta 0:00:01
   -------------------------------------- - 44.0/45.8 MB 6.6 MB/s eta 0:00:01
   -------------------------------------- - 44.3/45.8 MB 6.6 MB/s eta 0:00:01
   -------------------------------------- - 44.6/45.8 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  44.9/45.8 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  45.2/45.8 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  45.6/45.8 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  45.8/45.8 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  45.8/45.8 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  45.8/45.8 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 45.8/45.8 MB 5.9 MB/s eta 0:00:00
Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.3.2 scikit-learn-1.4.0 scipy-1.12.0 threadpoolctl-3.2.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Math Score'] = le.fit_transform(df['Math Score'])
newdf=df
df

,Math Score,Reading Score,Writing Score,Placement Score,Club Join Year,Placement,Offer Count
0,14,81,93,85,96,98,99
1,10,79,64,97,79,66,97
2,17,96,70,86,99,84,69
3,12,83,100,81,62,79,79
4,3,72,96,62,85,64,64
5,0,76,84,100,92,83,74
6,2,87,99,94,99,72,68
7,13,75,91,66,67,88,86
8,15,79,74,77,84,90,91
9,4,60,77,70,77,81,69
10,7,65,61,90,61,60,67
11,5,94,88,91,63,90,71
12,11,79,63,93,61,99,80
13,8,79,100,71,75,76,95
14,9,81,88,61,90,91,84
15,8,64,98,100,90,69,96
16,1,85,94,84,83,60,62
17,16,80,75,93,67,72,76
18,11,87,81,99,96,63,73
19,6,99,89,84,66,97,87

In [14]:
missing_values = ["Na", "na"]

In [16]:
df = pd.read_csv("Academic Performance.csv", na_values =missing_values)
df

,Math Score,Reading Score,Writing Score,Placement Score,Club Join Year,Placement,Offer Count
0,95,81,93,85,96,98,99
1,83,79,64,97,79,66,97
2,100,96,70,86,99,84,69
3,88,83,100,81,62,79,79
4,73,72,96,62,85,64,64
5,63,76,84,100,92,83,74
6,72,87,99,94,99,72,68
7,90,75,91,66,67,88,86
8,97,79,74,77,84,90,91
9,74,60,77,70,77,81,69
10,77,65,61,90,61,60,67
11,75,94,88,91,63,90,71
12,85,79,63,93,61,99,80
13,80,79,100,71,75,76,95
14,81,81,88,61,90,91,84
15,80,64,98,100,90,69,96
16,66,85,94,84,83,60,62
17,99,80,75,93,67,72,76
18,85,87,81,99,96,63,73
19,76,99,89,84,66,97,87